#!/usr/bin/env python3
"""
V8 Code Generator - Phase 2

Automatically generates optimization code from detected patterns using templates.

Input: Pattern detection (type, parameters, confidence)
Output: Executable script (Python or bash)

Templates supported:
1. Command retry wrapper
2. Directory navigation helper
3. Multi-command workflow
4. Cache operations
5. Persistent deduplication
"""

import os
import json
import sys
from pathlib import Path
from typing import Dict, Optional
from datetime import datetime

# Import external template modules
sys.path.insert(0, str(Path(__file__).parent))
from system_admin_templates import SYSTEM_ADMIN_TEMPLATES
from development_templates import DEVELOPMENT_TEMPLATES
from productivity_templates import PRODUCTIVITY_TEMPLATES
from file_management_templates import FILE_MANAGEMENT_TEMPLATES


class CodeGenerator:
    """Generate optimization code from patterns"""
    
    def __init__(self, templates_dir: Path = None, output_dir: Path = None):
        if templates_dir is None:
            templates_dir = Path(__file__).parent / 'templates'
        if output_dir is None:
            output_dir = Path.home() / '.openclaw/workspace/scripts'
        
        self.templates_dir = templates_dir
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Load templates
        self.templates = self._load_templates()
    
    def _load_templates(self) -> Dict:
        """Load code generation templates"""
        templates = {
            'command_retry': self._template_command_retry,
            'dir_navigation': self._template_dir_navigation,
            'multi_command': self._template_multi_command,
            'cache_operation': self._template_cache_operation,
            'deduplication': self._template_deduplication,
            'email_template': self._template_email_template,
            'email_shortcut': self._template_email_shortcut,
            'email_schedule': self._template_email_schedule,
            'meeting_automation': self._template_meeting_automation,
            'focus_block': self._template_focus_block,
            'meeting_workflow': self._template_meeting_workflow
        }
        
        # Add system admin templates (from external module)
        for name, func in SYSTEM_ADMIN_TEMPLATES.items():
            # Wrap external function to match our interface
            templates[name] = lambda pattern, f=func: f(pattern, self.output_dir)
        
        # Add development templates (from external module)
        for name, func in DEVELOPMENT_TEMPLATES.items():
            templates[name] = lambda pattern, f=func: f(pattern, self.output_dir)
        
        # Add productivity templates
        for name, func in PRODUCTIVITY_TEMPLATES.items():
            templates[name] = lambda pattern, f=func: f(pattern, self.output_dir)
        
        # Add file management templates
        for name, func in FILE_MANAGEMENT_TEMPLATES.items():
            templates[name] = lambda pattern, f=func: f(pattern, self.output_dir)
        
        return templates
    
    def generate(self, pattern: Dict) -> Optional[Dict]:
        """
        Generate code from a detected pattern.
        
        Args:
            pattern: {
                'type': 'command_retry',
                'command': 'curl',
                'occurrences': 15,
                'confidence': 0.85,
                'parameters': {...}
            }
        
        Returns:
            {
                'script_path': Path,
                'code': str,
                'language': 'bash' or 'python',
                'install_instructions': str
            }
        """
        pattern_type = pattern.get('type')
        
        if pattern_type not in self.templates:
            return None
        
        # Get template function
        template_fn = self.templates[pattern_type]
        
        # Generate code
        result = template_fn(pattern)
        
        if result:
            # Add metadata
            result['generated_at'] = datetime.now().isoformat()
            result['pattern'] = pattern
            result['confidence'] = pattern.get('confidence', 0.0)
        
        return result
    
    def _template_command_retry(self, pattern: Dict) -> Dict:
        """Generate command retry wrapper"""
        command = pattern.get('command', 'unknown')
        max_retries = pattern.get('parameters', {}).get('max_retries', 3)
        delay = pattern.get('parameters', {}).get('delay', 1)
        
        script_name = f"{command}_retry"
        script_path = self.output_dir / script_name
        
        code = f'''#!/bin/bash
#
# Auto-generated retry wrapper for: {command}
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

MAX_RETRIES={max_retries}
DELAY={delay}

attempt=1
while [ $attempt -le $MAX_RETRIES ]; do
    {command} "$@"
    exit_code=$?
    
    if [ $exit_code -eq 0 ]; then
        exit 0
    fi
    
    if [ $attempt -lt $MAX_RETRIES ]; then
        echo "Retrying {command} (attempt $((attempt+1))/$MAX_RETRIES)..." >&2
        sleep $DELAY
        attempt=$((attempt + 1))
    else
        echo "Failed after $MAX_RETRIES attempts" >&2
        exit $exit_code
    fi
done
'''
        
        install_instructions = f'''
# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add alias to ~/.zshrc:
   alias {command}='{script_path}'
4. Reload shell: source ~/.zshrc
'''
        
        return {
            'script_path': script_path,
            'script_name': script_name,
            'code': code,
            'language': 'bash',
            'install_instructions': install_instructions,
            'estimated_savings': f"{pattern.get('occurrences', 0) * 5} sec/week"
        }
    
    def _template_dir_navigation(self, pattern: Dict) -> Dict:
        """Generate directory navigation helper"""
        command = pattern.get('command', 'unknown')
        target_dir_var = pattern.get('parameters', {}).get('directory', 'TARGET_DIR')
        
        script_name = f"{command}_here"
        script_path = self.output_dir / script_name
        
        code = f'''#!/bin/bash
#
# Run {command} in specified directory
# Generated by V8 Code Generator
#

if [ $# -lt 2 ]; then
    echo "Usage: {script_name} <directory> <args>"
    exit 1
fi

TARGET_DIR="$1"
shift

if [ ! -d "$TARGET_DIR" ]; then
    echo "Directory not found: $TARGET_DIR"
    exit 1
fi

(cd "$TARGET_DIR" && {command} "$@")
'''
        
        install_instructions = f'''
# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add alias: alias {command}-here='{script_path}'
'''
        
        return {
            'script_path': script_path,
            'script_name': script_name,
            'code': code,
            'language': 'bash',
            'install_instructions': install_instructions,
            'estimated_savings': f"{pattern.get('occurrences', 0) * 10} sec/week"
        }
    
    def _template_multi_command(self, pattern: Dict) -> Dict:
        """Generate multi-command workflow alias"""
        workflow_name = pattern.get('name', 'workflow')
        commands = pattern.get('commands', [])
        
        if not commands:
            return None
        
        # Generate function code
        command_chain = ' && \\\n    '.join(commands)
        
        code = f'''# Add to ~/.zshrc

{workflow_name}() {{
    # Auto-generated workflow
    # Pattern confidence: {pattern.get('confidence', 0.0):.0%}
    
    {command_chain}
}}
'''
        
        install_instructions = f'''
# Installation:
1. Add function to ~/.zshrc
2. Reload: source ~/.zshrc
3. Usage: {workflow_name} [args]
'''
        
        return {
            'script_name': workflow_name,
            'code': code,
            'language': 'bash',
            'install_instructions': install_instructions,
            'estimated_savings': f"{pattern.get('occurrences', 0) * 15} sec/week"
        }
    
    def _template_cache_operation(self, pattern: Dict) -> Dict:
        """Generate caching wrapper (Python)"""
        operation = pattern.get('operation', 'expensive_op')
        ttl_minutes = pattern.get('parameters', {}).get('ttl_minutes', 60)
        
        code = f'''#!/usr/bin/env python3
"""
Auto-generated caching wrapper for: {operation}
Generated by V8 Code Generator
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path.home() / "workspace/integrations/autonomous_executor"))
from token_cache import TokenCache

cache = TokenCache(cache_dir=Path.home() / '.openclaw/workspace/cache/{operation}')

def cached_{operation}(key, *args, **kwargs):
    """Cached version of {operation}"""
    # Check cache
    cached = cache.get(key)
    if cached:
        return cached
    
    # Cache miss - execute operation
    result = {operation}_original(key, *args, **kwargs)
    
    # Cache result
    if result:
        cache.set(key, result, ttl_minutes={ttl_minutes})
    
    return result

# TODO: Import or define {operation}_original
'''
        
        return {
            'script_name': f'{operation}_cached.py',
            'code': code,
            'language': 'python',
            'install_instructions': 'Integration required with existing operation',
            'estimated_savings': f"~{pattern.get('occurrences', 0)} calls/week saved"
        }
    
    def _template_deduplication(self, pattern: Dict) -> Dict:
        """Generate deduplication logic (Python)"""
        operation = pattern.get('operation', 'send_notification')
        ttl_hours = pattern.get('parameters', {}).get('ttl_hours', 12)
        
        code = f'''#!/usr/bin/env python3
"""
Deduplication for: {operation}
Generated by V8 Code Generator
"""

from pathlib import Path
import sys
sys.path.insert(0, str(Path.home() / "workspace/integrations/autonomous_executor"))
from token_cache import TokenCache

dedup_cache = TokenCache(cache_dir=Path.home() / '.openclaw/workspace/cache/dedup')

def should_{operation}(key):
    """Check if operation should execute (not a duplicate)"""
    cached = dedup_cache.get(key)
    if cached:
        return False  # Skip duplicate
    return True

def mark_{operation}_done(key):
    """Mark operation as completed"""
    dedup_cache.set(key, {{'completed': True}}, ttl_minutes={ttl_hours * 60})
'''
        
        return {
            'script_name': f'{operation}_dedup.py',
            'code': code,
            'language': 'python',
            'install_instructions': 'Integration required with existing notification system',
            'estimated_savings': f"~{pattern.get('occurrences', 0)} duplicates/week prevented"
        }
    
    def _template_email_template(self, pattern: Dict) -> Optional[Dict]:
        """Generate email template script"""
        subject_pattern = pattern.get('subject_pattern', 'Template')
        name = 'email_' + subject_pattern.lower().replace(' ', '_')[:30]
        
        code = f'''#!/usr/bin/env python3
"""
Email Template: {subject_pattern}

Generated by V8 from detected email pattern.
Usage: {name} <recipient> [additional text]
"""

import sys
import subprocess

def send_email(recipient: str, extra_text: str = ""):
    subject = "{subject_pattern}"
    body = f"""Hi,

{{extra_text}}

Best,
Simon
"""
    
    # Use gog to send email
    cmd = ['gog', 'gmail', 'send', '--to', recipient, '--subject', subject, '--body', body]
    subprocess.run(cmd)
    print(f"✅ Sent: {{subject}} to {{recipient}}")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: {name} <recipient> [extra text]")
        sys.exit(1)
    
    recipient = sys.argv[1]
    extra = ' '.join(sys.argv[2:]) if len(sys.argv) > 2 else ""
    send_email(recipient, extra)
'''
        
        return {
            'code': code,
            'script_name': name,
            'language': 'python',
            'confidence': pattern.get('confidence', 0.80),
            'estimated_savings': f"{pattern.get('count', 5) * 2} min/week",
            'install_instructions': f'''1. Save to ~/.openclaw/workspace/scripts/{name}
2. chmod +x ~/.openclaw/workspace/scripts/{name}
3. Add to PATH or create alias: alias {name}="python3 ~/.openclaw/workspace/scripts/{name}"'''
        }
    
    def _template_email_shortcut(self, pattern: Dict) -> Optional[Dict]:
        """Generate email shortcut for frequent recipient"""
        recipient = pattern.get('recipient', 'contact@example.com')
        name = 'email_' + recipient.split('@')[0].lower()
        
        code = f'''#!/bin/bash
# Quick email to {recipient}
# Generated by V8 - you email this person {pattern.get('count', 5)}x

SUBJECT="$1"
BODY="$2"

if [ -z "$SUBJECT" ]; then
    echo "Usage: {name} <subject> [body]"
    exit 1
fi

# Use gog to compose email
gog gmail compose --to "{recipient}" --subject "$SUBJECT" --body "$BODY"
echo "✅ Email composed to {recipient}"
'''
        
        return {
            'code': code,
            'script_name': name,
            'language': 'bash',
            'confidence': pattern.get('confidence', 0.80),
            'estimated_savings': f"{pattern.get('count', 5)} min/week",
            'install_instructions': f'''1. Save to ~/.openclaw/workspace/scripts/{name}
2. chmod +x ~/.openclaw/workspace/scripts/{name}
3. Add to PATH'''
        }
    
    def _template_email_schedule(self, pattern: Dict) -> Optional[Dict]:
        """Generate scheduled email reminder"""
        time = pattern.get('time', '9:00')
        pattern_desc = pattern.get('pattern', 'weekly')
        name = f'email_reminder_{pattern_desc}'
        
        code = f'''#!/usr/bin/env python3
"""
Scheduled Email Reminder: {pattern_desc} at {time}

Generated by V8 from detected email timing pattern.
Add to crontab or LaunchAgent to automate.
"""

import subprocess
from datetime import datetime

def send_reminder():
    now = datetime.now()
    subject = f"Reminder: {{now.strftime('%A, %B %d')}}"
    body = """Don't forget your {pattern_desc} task!"""
    
    # Send via OpenClaw message
    subprocess.run(['openclaw', 'message', 'send', '--telegram', '8451730454', '--text', subject])
    print(f"✅ Reminder sent: {{subject}}")

if __name__ == '__main__':
    send_reminder()
'''
        
        return {
            'code': code,
            'script_name': name,
            'language': 'python',
            'confidence': pattern.get('confidence', 0.75),
            'estimated_savings': "5 min/week (prevents forgotten tasks)",
            'install_instructions': f'''1. Save to ~/.openclaw/workspace/scripts/{name}
2. chmod +x ~/.openclaw/workspace/scripts/{name}
3. Add to cron: openclaw cron create "{name}" "0 {time.split(':')[0]} * * *" "python3 ~/.openclaw/workspace/scripts/{name}"'''
        }
    
    def _template_meeting_automation(self, pattern: Dict) -> Optional[Dict]:
        """Generate meeting prep/follow-up automation"""
        event_pattern = pattern.get('event_pattern', 'Meeting')
        name = 'meeting_' + event_pattern.lower().replace(' ', '_')[:30]
        
        code = f'''#!/usr/bin/env python3
"""
Meeting Automation: {event_pattern}

Generated by V8 from recurring calendar event.
Send agenda 2 hours before, summary 1 hour after.
"""

import subprocess
from datetime import datetime, timedelta
import json

def get_upcoming_meetings():
    # Use gog to fetch today's calendar
    result = subprocess.run(
        ['gog', 'calendar', 'events', '--account', 'lacrosseguy76665@gmail.com', 'primary'],
        capture_output=True,
        text=True
    )
    
    # Find meetings matching pattern
    # (Simplified - real version would parse JSON)
    if "{event_pattern}" in result.stdout:
        return True
    return False

def send_prep():
    """Send meeting prep 2 hours before"""
    msg = f"Reminder: {event_pattern} in 2 hours. Review agenda!"
    subprocess.run(['openclaw', 'message', 'send', '--telegram', '8451730454', '--text', msg])
    print(f"✅ Prep reminder sent")

def send_followup():
    """Send follow-up reminder 1 hour after"""
    msg = f"Don't forget: Send summary for {event_pattern}"
    subprocess.run(['openclaw', 'message', 'send', '--telegram', '8451730454', '--text', msg])
    print(f"✅ Follow-up reminder sent")

if __name__ == '__main__':
    import sys
    action = sys.argv[1] if len(sys.argv) > 1 else 'prep'
    
    if action == 'prep':
        send_prep()
    elif action == 'followup':
        send_followup()
'''
        
        return {
            'code': code,
            'script_name': name,
            'language': 'python',
            'confidence': pattern.get('confidence', 0.85),
            'estimated_savings': f"{pattern.get('count', 4) * 10} min/month",
            'install_instructions': f'''1. Save to ~/.openclaw/workspace/scripts/{name}
2. chmod +x ~/.openclaw/workspace/scripts/{name}
3. Hook into calendar (manual for now, auto-hook in V9)'''
        }
    
    def _template_focus_block(self, pattern: Dict) -> Optional[Dict]:
        """Generate focus time block protection"""
        day = pattern.get('day', 'Monday')
        time = pattern.get('time', '9:00')
        duration = pattern.get('duration', 60)
        name = f'focus_block_{day.lower()}'
        
        code = f'''#!/usr/bin/env python3
"""
Focus Time Block: {day} {time} ({duration} min)

Generated by V8 from detected calendar gap.
Blocks calendar and enables DND mode.
"""

import subprocess
from datetime import datetime, timedelta

def block_calendar():
    """Add focus block to calendar"""
    start = datetime.now().replace(hour=int("{time}".split(':')[0]), minute=int("{time}".split(':')[1]), second=0)
    end = start + timedelta(minutes={duration})
    
    # Add to Google Calendar via gog
    subprocess.run([
        'gog', 'calendar', 'events', 'create',
        '--account', 'lacrosseguy76665@gmail.com',
        '--summary', 'Focus Time',
        '--start', start.isoformat(),
        '--end', end.isoformat(),
        '--description', 'Protected focus time - no meetings'
    ])
    
    print(f"✅ Focus block added: {{start.strftime('%I:%M %p')}} - {{end.strftime('%I:%M %p')}}")

if __name__ == '__main__':
    block_calendar()
'''
        
        return {
            'code': code,
            'script_name': name,
            'language': 'python',
            'confidence': pattern.get('confidence', 0.80),
            'estimated_savings': f"{duration} min/week (protected focus time)",
            'install_instructions': f'''1. Save to ~/.openclaw/workspace/scripts/{name}
2. chmod +x ~/.openclaw/workspace/scripts/{name}
3. Run weekly: openclaw cron create "{name}" "0 8 * * 1" "python3 ~/.openclaw/workspace/scripts/{name}"'''
        }
    
    def _template_meeting_workflow(self, pattern: Dict) -> Optional[Dict]:
        """Generate category-specific meeting workflow"""
        category = pattern.get('category', 'client')
        name = f'{category}_meeting_workflow'
        
        code = f'''#!/usr/bin/env python3
"""
{category.title()} Meeting Workflow

Generated by V8 from {pattern.get('count', 5)} {category} meetings.
Automated prep, execution, and follow-up.
"""

import subprocess
import sys

def prep():
    """Pre-meeting checklist"""
    checklist = [
        "Review previous notes",
        "Prepare agenda",
        "Test video/audio"
    ]
    
    msg = f"**{category.title()} Meeting Prep:**\\n" + "\\n".join(f"- {{item}}" for item in checklist)
    subprocess.run(['openclaw', 'message', 'send', '--telegram', '8451730454', '--text', msg])
    print("✅ Prep checklist sent")

def followup():
    """Post-meeting actions"""
    msg = f"**{category.title()} Meeting Follow-up:**\\n- Send summary\\n- Update tasks\\n- Schedule next meeting"
    subprocess.run(['openclaw', 'message', 'send', '--telegram', '8451730454', '--text', msg])
    print("✅ Follow-up reminder sent")

if __name__ == '__main__':
    action = sys.argv[1] if len(sys.argv) > 1 else 'prep'
    
    if action == 'prep':
        prep()
    elif action == 'followup':
        followup()
'''
        
        return {
            'code': code,
            'script_name': name,
            'language': 'python',
            'confidence': pattern.get('confidence', 0.75),
            'estimated_savings': f"{pattern.get('count', 5) * 5} min/month",
            'install_instructions': f'''1. Save to ~/.openclaw/workspace/scripts/{name}
2. chmod +x ~/.openclaw/workspace/scripts/{name}
3. Run manually or hook to calendar events'''
        }


def main():
    """Test code generation"""
    generator = CodeGenerator()
    
    # Test pattern 1: Command retry
    test_pattern = {
        'type': 'command_retry',
        'command': 'wget',
        'occurrences': 15,
        'confidence': 0.85,
        'parameters': {
            'max_retries': 3,
            'delay': 2
        }
    }
    
    print("🔧 V8 Code Generator - Test Run")
    print("=" * 60)
    print()
    
    result = generator.generate(test_pattern)
    
    if result:
        print(f"Generated: {result['script_name']}")
        print(f"Language: {result['language']}")
        print(f"Confidence: {result['confidence']:.0%}")
        print(f"Estimated savings: {result['estimated_savings']}")
        print()
        print("Generated Code:")
        print("-" * 60)
        print(result['code'])
