#!/usr/bin/env python3
"""
Development Templates for V8 Code Generator

Provides 5 new template types:
1. test_runner - Auto-run tests before git commit
2. linter_precommit - Format/lint code before push  
3. dependency_update - Check for outdated packages weekly
4. build_optimization - Cache build artifacts
5. hot_reload - Auto-restart dev server on file changes
"""

from pathlib import Path
from typing import Dict


def template_test_runner(pattern: Dict, output_dir: Path) -> Dict:
    """Generate automated test runner for pre-commit"""
    test_command = pattern.get('test_command', 'npm test')
    project_dir = pattern.get('project_dir', '.')
    
    script_name = "run_tests_precommit"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated test runner (pre-commit hook)
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

PROJECT_DIR="{project_dir}"
TEST_CMD="{test_command}"

cd "$PROJECT_DIR" || exit 1

echo "🧪 Running tests before commit..."

if $TEST_CMD; then
    echo "✅ All tests passed"
    exit 0
else
    echo "❌ Tests failed - commit blocked"
    echo "Fix failing tests before committing"
    exit 1
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Install as git hook:
   ln -sf {script_path} {project_dir}/.git/hooks/pre-commit
4. Tests will run automatically before each commit
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '30 min/week'
    }


def template_linter_precommit(pattern: Dict, output_dir: Path) -> Dict:
    """Generate linter/formatter pre-commit hook"""
    lint_command = pattern.get('lint_command', 'npm run lint')
    format_command = pattern.get('format_command', 'npm run format')
    project_dir = pattern.get('project_dir', '.')
    
    script_name = "lint_precommit"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated linter/formatter pre-commit hook
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

PROJECT_DIR="{project_dir}"
LINT_CMD="{lint_command}"
FORMAT_CMD="{format_command}"

cd "$PROJECT_DIR" || exit 1

echo "🎨 Formatting code..."
$FORMAT_CMD

echo "🔍 Running linter..."
if $LINT_CMD; then
    echo "✅ Linting passed"
    
    # Stage formatted files
    git add -u
    
    exit 0
else
    echo "❌ Linting failed - commit blocked"
    echo "Fix linting errors before committing"
    exit 1
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Install as git hook:
   ln -sf {script_path} {project_dir}/.git/hooks/pre-commit
4. Code will be formatted and linted automatically
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '20 min/week'
    }


def template_dependency_update(pattern: Dict, output_dir: Path) -> Dict:
    """Generate dependency update checker"""
    package_manager = pattern.get('package_manager', 'npm')
    project_dir = pattern.get('project_dir', '.')
    notify = pattern.get('notify', True)
    
    script_name = "check_dependencies"
    script_path = output_dir / f"{script_name}.sh"
    
    # Package manager specific commands
    if package_manager == 'npm':
        check_cmd = 'npm outdated || true'
        update_cmd = 'npm update'
    elif package_manager == 'pip':
        check_cmd = 'pip list --outdated'
        update_cmd = 'pip install --upgrade'
    elif package_manager == 'brew':
        check_cmd = 'brew outdated'
        update_cmd = 'brew upgrade'
    else:
        check_cmd = f'{package_manager} outdated'
        update_cmd = f'{package_manager} update'
    
    notify_code = '''
    # Notify via Telegram
    if [ -f ~/.openclaw/workspace/integrations/intelligence/v8_meta_learning/telegram_notifier.py ]; then
        python3 ~/.openclaw/workspace/integrations/intelligence/v8_meta_learning/telegram_notifier.py "📦 $count outdated dependencies found. Run: $UPDATE_CMD"
    fi''' if notify else '    # Notification disabled'
    
    code = f'''#!/bin/bash
#
# Auto-generated dependency update checker
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

PROJECT_DIR="{project_dir}"
PKG_MANAGER="{package_manager}"
CHECK_CMD="{check_cmd}"
UPDATE_CMD="{update_cmd}"

cd "$PROJECT_DIR" || exit 1

echo "📦 Checking for outdated dependencies..."

output=$($CHECK_CMD)

if [ -z "$output" ]; then
    echo "✅ All dependencies up to date"
    exit 0
fi

echo "$output"

count=$(echo "$output" | wc -l)
echo ""
echo "⚠️  $count outdated dependencies found"
echo "To update: $UPDATE_CMD"
{notify_code}

exit 0
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add to crontab (run weekly on Monday):
   0 9 * * 1 {script_path}
4. Or run manually: {script_path}
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '15 min/week'
    }


def template_build_optimization(pattern: Dict, output_dir: Path) -> Dict:
    """Generate build cache optimization script"""
    build_command = pattern.get('build_command', 'npm run build')
    cache_dir = pattern.get('cache_dir', '.cache')
    project_dir = pattern.get('project_dir', '.')
    
    script_name = "build_with_cache"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated build script with caching
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

PROJECT_DIR="{project_dir}"
BUILD_CMD="{build_command}"
CACHE_DIR="{cache_dir}"

cd "$PROJECT_DIR" || exit 1

# Create cache directory
mkdir -p "$CACHE_DIR"

echo "🔨 Building with cache..."

# Check if cache exists and is fresh
cache_hash="$CACHE_DIR/build.hash"
current_hash=$(find . -type f -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx" | sort | xargs md5 2>/dev/null | md5)

if [ -f "$cache_hash" ]; then
    cached_hash=$(cat "$cache_hash")
    
    if [ "$current_hash" = "$cached_hash" ]; then
        echo "✅ Build cache is fresh, skipping build"
        exit 0
    fi
fi

echo "Building..."
start_time=$(date +%s)

if $BUILD_CMD; then
    end_time=$(date +%s)
    duration=$((end_time - start_time))
    
    echo "✅ Build complete in ${{duration}}s"
    
    # Update cache hash
    echo "$current_hash" > "$cache_hash"
    
    exit 0
else
    echo "❌ Build failed"
    exit 1
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Use instead of direct build command:
   {script_path}
4. Or alias in package.json:
   "build:cached": "{script_path}"
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '45 min/week'
    }


def template_hot_reload(pattern: Dict, output_dir: Path) -> Dict:
    """Generate hot reload watcher for development"""
    watch_dir = pattern.get('watch_dir', './src')
    restart_command = pattern.get('restart_command', 'npm run dev')
    extensions = pattern.get('extensions', ['js', 'ts', 'jsx', 'tsx', 'json'])
    
    script_name = "hot_reload_watcher"
    script_path = output_dir / f"{script_name}.sh"
    
    extensions_str = ' -o '.join([f'-name "*.{ext}"' for ext in extensions])
    
    code = f'''#!/bin/bash
#
# Auto-generated hot reload watcher
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

WATCH_DIR="{watch_dir}"
RESTART_CMD="{restart_command}"
PID_FILE="/tmp/hotreload_dev_server.pid"

echo "👀 Watching $WATCH_DIR for changes..."

# Kill existing dev server
if [ -f "$PID_FILE" ]; then
    old_pid=$(cat "$PID_FILE")
    kill "$old_pid" 2>/dev/null
fi

# Start dev server in background
$RESTART_CMD &
new_pid=$!
echo $new_pid > "$PID_FILE"

echo "✅ Dev server started (PID: $new_pid)"

# Watch for file changes using fswatch (install: brew install fswatch)
if command -v fswatch &> /dev/null; then
    fswatch -o "$WATCH_DIR" | while read -r event; do
        echo "🔄 Changes detected, restarting..."
        
        # Kill old server
        if [ -f "$PID_FILE" ]; then
            old_pid=$(cat "$PID_FILE")
            kill "$old_pid" 2>/dev/null
        fi
        
        # Start new server
        $RESTART_CMD &
        new_pid=$!
        echo $new_pid > "$PID_FILE"
        
        echo "✅ Dev server restarted (PID: $new_pid)"
    done
else
    echo "❌ fswatch not found. Install with: brew install fswatch"
    
    # Fallback: simple polling
    echo "Using fallback polling (slower)..."
    
    last_hash=$(find "$WATCH_DIR" -type f \\( {extensions_str} \\) | xargs md5 2>/dev/null | md5)
    
    while true; do
        sleep 2
        
        current_hash=$(find "$WATCH_DIR" -type f \\( {extensions_str} \\) | xargs md5 2>/dev/null | md5)
        
        if [ "$current_hash" != "$last_hash" ]; then
            echo "🔄 Changes detected, restarting..."
            
            # Kill old server
            if [ -f "$PID_FILE" ]; then
                old_pid=$(cat "$PID_FILE")
                kill "$old_pid" 2>/dev/null
            fi
            
            # Start new server
            $RESTART_CMD &
            new_pid=$!
            echo $new_pid > "$PID_FILE"
            
            echo "✅ Dev server restarted (PID: $new_pid)"
            
            last_hash=$current_hash
        fi
    done
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Install fswatch: brew install fswatch (optional, better performance)
4. Run during development: {script_path}
5. Stop with Ctrl+C
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '60 min/week'
    }


# Template registry for easy lookup
DEVELOPMENT_TEMPLATES = {
    'test_runner': template_test_runner,
    'linter_precommit': template_linter_precommit,
    'dependency_update': template_dependency_update,
    'build_optimization': template_build_optimization,
    'hot_reload': template_hot_reload
}
