#!/usr/bin/env python3
"""
File Management Templates for V8 Code Generator

5 templates:
1. duplicate_finder - Find/remove duplicate files
2. smart_archiving - Move old files to archive
3. screenshot_organizer - Auto-organize screenshots
4. download_cleaner - Clean downloads folder
5. file_deduplication - Remove duplicate files by hash
"""

from pathlib import Path
from typing import Dict


def template_duplicate_finder(pattern: Dict, output_dir: Path) -> Dict:
    """Generate duplicate file finder"""
    scan_dirs = pattern.get('scan_dirs', ['~/Documents', '~/Downloads'])
    min_size_mb = pattern.get('min_size_mb', 1)
    
    script_name = "find_duplicates"
    script_path = output_dir / f"{script_name}.sh"
    
    dirs_str = ' '.join([f'"{d}"' for d in scan_dirs])
    
    code = f'''#!/bin/bash
#
# Auto-generated duplicate file finder
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

SCAN_DIRS=({dirs_str})
MIN_SIZE_MB={min_size_mb}
MIN_SIZE_BYTES=$((MIN_SIZE_MB * 1024 * 1024))

echo "🔍 Finding duplicate files (>${{MIN_SIZE_MB}}MB)..."

temp_file=$(mktemp)

# Find all files and compute MD5 hashes
for dir in "${{SCAN_DIRS[@]}}"; do
    expanded=$(eval echo "$dir")
    
    if [ -d "$expanded" ]; then
        echo "Scanning: $expanded"
        
        find "$expanded" -type f -size +${{MIN_SIZE_BYTES}}c -exec md5 {{}} \\; 2>/dev/null | \\
        awk '{{
            hash = $NF
            gsub(/^.*= /, "", hash)
            file = $0
            gsub(/ =.*$/, "", file)
            print hash "\\t" file
        }}' >> "$temp_file"
    fi
done

# Find duplicates
echo ""
echo "Duplicate files found:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

duplicates=$(sort "$temp_file" | uniq -d -w 32)

if [ -z "$duplicates" ]; then
    echo "✅ No duplicates found"
else
    echo "$duplicates" | while IFS=$'\\t' read -r hash file; do
        size=$(du -h "$file" 2>/dev/null | cut -f1)
        echo "$size\\t$file"
    done | sort -rh
    
    echo ""
    echo "To remove duplicates, review the files above and delete manually."
fi

rm "$temp_file"
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Run weekly: {script_path}
4. Review output before deleting files
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '30 min/week'
    }


def template_smart_archiving(pattern: Dict, output_dir: Path) -> Dict:
    """Generate smart file archiving"""
    watch_dirs = pattern.get('watch_dirs', ['~/Documents'])
    archive_dir = pattern.get('archive_dir', '~/Archive')
    days_old = pattern.get('days_old', 90)
    
    script_name = "auto_archive"
    script_path = output_dir / f"{script_name}.sh"
    
    dirs_str = ' '.join([f'"{d}"' for d in watch_dirs])
    
    code = f'''#!/bin/bash
#
# Auto-generated smart archiving script
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

WATCH_DIRS=({dirs_str})
ARCHIVE_DIR="{archive_dir}"
DAYS_OLD={days_old}

# Expand tilde
ARCHIVE_DIR=$(eval echo "$ARCHIVE_DIR")

# Create archive directory
mkdir -p "$ARCHIVE_DIR"

echo "📦 Archiving files older than $DAYS_OLD days..."

archived_count=0
archived_size=0

for dir in "${{WATCH_DIRS[@]}}"; do
    expanded=$(eval echo "$dir")
    
    if [ ! -d "$expanded" ]; then
        continue
    fi
    
    echo "Scanning: $expanded"
    
    # Find files not accessed in DAYS_OLD days
    while IFS= read -r -d '' file; do
        # Get file size
        size=$(stat -f%z "$file" 2>/dev/null || echo 0)
        
        # Create archive path (preserve directory structure)
        rel_path="${{file#$expanded/}}"
        archive_path="$ARCHIVE_DIR/$(dirname "$rel_path")"
        
        mkdir -p "$archive_path"
        
        # Move file to archive
        if mv "$file" "$archive_path/"; then
            archived_count=$((archived_count + 1))
            archived_size=$((archived_size + size))
        fi
    done < <(find "$expanded" -type f -atime +$DAYS_OLD -print0 2>/dev/null)
done

if [ $archived_count -gt 0 ]; then
    archived_mb=$((archived_size / 1024 / 1024))
    echo "✅ Archived $archived_count files (${{archived_mb}} MB)"
else
    echo "✅ No files to archive"
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add to crontab (run monthly):
   0 3 1 * * {script_path}
4. Files are moved to {archive_dir} (not deleted)
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '20 min/month'
    }


def template_screenshot_organizer(pattern: Dict, output_dir: Path) -> Dict:
    """Generate screenshot organization automation"""
    screenshot_dir = pattern.get('screenshot_dir', '~/Desktop')
    dest_dir = pattern.get('dest_dir', '~/Pictures/Screenshots')
    
    script_name = "organize_screenshots"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated screenshot organizer
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

SCREENSHOT_DIR="{screenshot_dir}"
DEST_DIR="{dest_dir}"

# Expand tilde
SCREENSHOT_DIR=$(eval echo "$SCREENSHOT_DIR")
DEST_DIR=$(eval echo "$DEST_DIR")

# Create destination directory
mkdir -p "$DEST_DIR"

echo "📸 Organizing screenshots..."

moved_count=0

# Find screenshot files (macOS naming pattern)
find "$SCREENSHOT_DIR" -maxdepth 1 -name "Screen Shot *.png" -o -name "Screenshot *.png" | while read -r file; do
    # Extract date from filename (format: Screen Shot 2026-04-13 at 5.30.15 PM.png)
    if [[ $(basename "$file") =~ ([0-9]{{4}}-[0-9]{{2}}-[0-9]{{2}}) ]]; then
        date="${{BASH_REMATCH[1]}}"
        year=$(echo "$date" | cut -d'-' -f1)
        month=$(echo "$date" | cut -d'-' -f2)
        
        # Create year/month directory
        target_dir="$DEST_DIR/$year/$month"
        mkdir -p "$target_dir"
        
        # Move screenshot
        if mv "$file" "$target_dir/"; then
            moved_count=$((moved_count + 1))
        fi
    fi
done

if [ $moved_count -gt 0 ]; then
    echo "✅ Organized $moved_count screenshots"
else
    echo "✅ No screenshots to organize"
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add to crontab (run daily):
   0 22 * * * {script_path}
4. Screenshots will be organized by date
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '10 min/week'
    }


def template_download_cleaner(pattern: Dict, output_dir: Path) -> Dict:
    """Generate downloads folder cleaner"""
    downloads_dir = pattern.get('downloads_dir', '~/Downloads')
    keep_days = pattern.get('keep_days', 30)
    
    script_name = "clean_downloads"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated downloads cleaner
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

DOWNLOADS_DIR="{downloads_dir}"
KEEP_DAYS={keep_days}

# Expand tilde
DOWNLOADS_DIR=$(eval echo "$DOWNLOADS_DIR")

echo "🧹 Cleaning downloads folder (keep last $KEEP_DAYS days)..."

if [ ! -d "$DOWNLOADS_DIR" ]; then
    echo "❌ Downloads directory not found: $DOWNLOADS_DIR"
    exit 1
fi

# Move old files to trash
deleted_count=0
freed_size=0

find "$DOWNLOADS_DIR" -maxdepth 1 -type f -mtime +$KEEP_DAYS | while read -r file; do
    size=$(stat -f%z "$file" 2>/dev/null || echo 0)
    
    # Use trash command if available (brew install trash)
    if command -v trash &> /dev/null; then
        trash "$file"
    else
        # Fallback: move to macOS trash
        osascript -e "tell application \\"Finder\\" to delete POSIX file \\"$file\\"" 2>/dev/null
    fi
    
    if [ $? -eq 0 ]; then
        deleted_count=$((deleted_count + 1))
        freed_size=$((freed_size + size))
    fi
done

if [ $deleted_count -gt 0 ]; then
    freed_mb=$((freed_size / 1024 / 1024))
    echo "✅ Removed $deleted_count files (${{freed_mb}} MB)"
else
    echo "✅ No old files to remove"
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Optional: brew install trash (safer deletion)
4. Add to crontab (run weekly):
   0 3 * * 0 {script_path}
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '15 min/week'
    }


def template_file_deduplication(pattern: Dict, output_dir: Path) -> Dict:
    """Generate file deduplication script (hardlink duplicates)"""
    scan_dir = pattern.get('scan_dir', '~/Documents')
    min_size_mb = pattern.get('min_size_mb', 5)
    
    script_name = "deduplicate_files"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated file deduplication script
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

SCAN_DIR="{scan_dir}"
MIN_SIZE_MB={min_size_mb}
MIN_SIZE_BYTES=$((MIN_SIZE_MB * 1024 * 1024))

# Expand tilde
SCAN_DIR=$(eval echo "$SCAN_DIR")

echo "🔗 Deduplicating files in: $SCAN_DIR"
echo "Minimum size: ${{MIN_SIZE_MB}}MB"
echo ""

# Create temporary file for hashes
temp_file=$(mktemp)

# Find all files and compute hashes
find "$SCAN_DIR" -type f -size +${{MIN_SIZE_BYTES}}c -exec md5 {{}} \\; 2>/dev/null | \\
awk '{{
    hash = $NF
    gsub(/^.*= /, "", hash)
    file = $0
    gsub(/ =.*$/, "", file)
    print hash "\\t" file
}}' > "$temp_file"

# Find and deduplicate
saved_space=0
dedup_count=0

# Group files by hash
sort "$temp_file" | awk -F'\\t' '{{
    hash = $1
    file = $2
    files[hash] = files[hash] ? files[hash] "\\n" file : file
}}
END {{
    for (hash in files) {{
        if (files[hash] ~ /\\n/) {{
            print files[hash]
            print "---"
        }}
    }}
}}' | while IFS= read -r line; do
    if [ "$line" = "---" ]; then
        # Process group of duplicates
        if [ ${{#group[@]}} -gt 1 ]; then
            # Keep first file, hardlink others
            master="${{group[0]}}"
            
            for ((i=1; i<${{#group[@]}}; i++)); do
                dup="${{group[$i]}}"
                
                # Get file size
                size=$(stat -f%z "$dup" 2>/dev/null || echo 0)
                
                # Remove duplicate and create hardlink
                rm "$dup"
                ln "$master" "$dup"
                
                if [ $? -eq 0 ]; then
                    dedup_count=$((dedup_count + 1))
                    saved_space=$((saved_space + size))
                    echo "Linked: $dup → $master"
                fi
            done
        fi
        
        group=()
    else
        group+=("$line")
    fi
done

rm "$temp_file"

if [ $dedup_count -gt 0 ]; then
    saved_mb=$((saved_space / 1024 / 1024))
    echo ""
    echo "✅ Deduplicated $dedup_count files"
    echo "💾 Saved ${{saved_mb}} MB"
else
    echo "✅ No duplicates found"
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Run monthly: {script_path}
4. Uses hardlinks (safe, reversible)
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '25 min/month'
    }


# Template registry
FILE_MANAGEMENT_TEMPLATES = {
    'duplicate_finder': template_duplicate_finder,
    'smart_archiving': template_smart_archiving,
    'screenshot_organizer': template_screenshot_organizer,
    'download_cleaner': template_download_cleaner,
    'file_deduplication': template_file_deduplication
}
