#!/usr/bin/env python3
"""
Productivity Templates for V8 Code Generator

4 templates:
1. focus_mode - Block distractions during focus time
2. context_switch - Save/restore app states  
3. pomodoro_timer - 25-min work blocks
4. daily_standup - Morning task review
"""

from pathlib import Path
from typing import Dict


def template_focus_mode(pattern: Dict, output_dir: Path) -> Dict:
    """Generate focus mode automation"""
    duration_minutes = pattern.get('duration', 90)
    block_apps = pattern.get('block_apps', ['Slack', 'Discord', 'Mail'])
    
    script_name = "focus_mode"
    script_path = output_dir / f"{script_name}.sh"
    
    apps_str = ' '.join([f'"{app}"' for app in block_apps])
    
    code = f'''#!/bin/bash
#
# Auto-generated focus mode script
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

DURATION={duration_minutes}
BLOCK_APPS=({apps_str})

echo "🎯 Entering focus mode for $DURATION minutes..."

# Quit distracting apps
for app in "${{BLOCK_APPS[@]}}"; do
    if pgrep -x "$app" > /dev/null; then
        echo "Quitting: $app"
        osascript -e "quit app \\"$app\\""
    fi
done

# Enable Do Not Disturb (macOS 12+)
shortcuts run "Set Focus" 2>/dev/null || echo "⚠️  Set Focus shortcut not found"

# Start timer
echo "✅ Focus mode active"
echo "Timer ends at: $(date -v+${{DURATION}}M +'%H:%M')"

# Wait for duration
sleep $(( DURATION * 60 ))

# Disable Do Not Disturb
shortcuts run "Turn Off Focus" 2>/dev/null

echo "✅ Focus mode complete!"

# Optional: Send completion notification
if [ -f ~/.openclaw/workspace/integrations/intelligence/v8_meta_learning/telegram_notifier.py ]; then
    python3 ~/.openclaw/workspace/integrations/intelligence/v8_meta_learning/telegram_notifier.py "✅ Focus session complete ($DURATION min)"
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Run when starting deep work: {script_path}
4. Or schedule via calendar automation
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': f'{duration_minutes} min/session'
    }


def template_context_switch(pattern: Dict, output_dir: Path) -> Dict:
    """Generate context switching automation"""
    contexts = pattern.get('contexts', {
        'coding': ['VSCode', 'Terminal', 'Chrome'],
        'meetings': ['Zoom', 'Calendar', 'Notes'],
        'writing': ['Obsidian', 'Chrome', 'Music']
    })
    
    script_name = "context_switch"
    script_path = output_dir / f"{script_name}.py"
    
    contexts_json = str(contexts).replace("'", '"')
    
    code = f'''#!/usr/bin/env python3
#
# Auto-generated context switching script
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

import subprocess
import sys
import json
from pathlib import Path

CONTEXTS = {contexts_json}
STATE_FILE = Path.home() / '.openclaw/workspace/.context_state.json'

def save_context(name):
    """Save current open applications"""
    # Get running apps
    result = subprocess.run(['osascript', '-e', 'tell application "System Events" to get name of every application process'], 
                          capture_output=True, text=True)
    running_apps = result.stdout.strip().split(', ')
    
    state = {{
        'name': name,
        'apps': running_apps
    }}
    
    STATE_FILE.parent.mkdir(exist_ok=True)
    with open(STATE_FILE, 'w') as f:
        json.dump(state, f)
    
    print(f"✅ Saved context: {{name}}")

def load_context(name):
    """Load and activate a context"""
    if name not in CONTEXTS:
        print(f"❌ Unknown context: {{name}}")
        print(f"Available: {{', '.join(CONTEXTS.keys())}}")
        return
    
    apps = CONTEXTS[name]
    
    print(f"🔄 Switching to: {{name}}")
    
    # Close apps not in target context
    # (Optional - commented out to avoid disruption)
    # current_apps = subprocess.run(...).stdout.split(', ')
    # for app in current_apps:
    #     if app not in apps:
    #         subprocess.run(['osascript', '-e', f'quit app "{{app}}"'])
    
    # Open target apps
    for app in apps:
        print(f"Opening: {{app}}")
        subprocess.run(['open', '-a', app])
    
    print(f"✅ Context loaded: {{name}}")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: context_switch.py <context_name>")
        print(f"Available contexts: {{', '.join(CONTEXTS.keys())}}")
        sys.exit(1)
    
    context_name = sys.argv[1]
    load_context(context_name)
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Usage: {script_path} coding
4. Available contexts: {', '.join(contexts.keys())}
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'python',
        'install_instructions': install,
        'estimated_savings': '30 min/week'
    }


def template_pomodoro_timer(pattern: Dict, output_dir: Path) -> Dict:
    """Generate pomodoro timer"""
    work_minutes = pattern.get('work_minutes', 25)
    break_minutes = pattern.get('break_minutes', 5)
    long_break_minutes = pattern.get('long_break_minutes', 15)
    cycles = pattern.get('cycles', 4)
    
    script_name = "pomodoro"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated Pomodoro timer
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

WORK_MIN={work_minutes}
BREAK_MIN={break_minutes}
LONG_BREAK_MIN={long_break_minutes}
CYCLES={cycles}

echo "🍅 Starting Pomodoro: $CYCLES cycles"
echo "Work: ${{WORK_MIN}}m | Break: ${{BREAK_MIN}}m | Long break: ${{LONG_BREAK_MIN}}m"
echo ""

for cycle in $(seq 1 $CYCLES); do
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🍅 Cycle $cycle/$CYCLES - WORK TIME"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    # Work session
    osascript -e "display notification \\"${{WORK_MIN}} minutes of focus\\" with title \\"🍅 Pomodoro - Work\\""
    sleep $(( WORK_MIN * 60 ))
    
    # Break
    if [ $cycle -eq $CYCLES ]; then
        # Long break after last cycle
        echo "✅ Cycle $cycle complete - LONG BREAK (${{LONG_BREAK_MIN}}m)"
        osascript -e "display notification \\"Take a long break!\\" with title \\"✅ All cycles complete\\""
        sleep $(( LONG_BREAK_MIN * 60 ))
    else
        # Short break
        echo "✅ Cycle $cycle complete - SHORT BREAK (${{BREAK_MIN}}m)"
        osascript -e "display notification \\"Take a short break\\" with title \\"✅ Cycle $cycle done\\""
        sleep $(( BREAK_MIN * 60 ))
    fi
    
    echo ""
done

echo "🎉 Pomodoro session complete!"
osascript -e "display notification \\"Great work!\\" with title \\"🎉 Session Complete\\""

# Optional: Log to file
echo "$(date '+%Y-%m-%d %H:%M') - Completed $CYCLES pomodoros" >> ~/.pomodoro_log.txt
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Run: {script_path}
4. Work in focused {work_minutes}-minute blocks
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': f'{work_minutes * cycles} min/session'
    }


def template_daily_standup(pattern: Dict, output_dir: Path) -> Dict:
    """Generate daily standup automation"""
    standup_time = pattern.get('standup_time', '09:00')
    
    script_name = "daily_standup"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated daily standup script
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

echo "📋 Daily Standup - $(date +'%A, %B %d')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check calendar for today
echo "📅 Today's calendar:"
if command -v openclaw &> /dev/null; then
    openclaw message send --telegram 8451730454 --text "**Daily Standup**\\n\\nWhat's on the calendar today?" --quiet
else
    echo "  (Install OpenClaw for automatic calendar summary)"
fi
echo ""

# Check pending tasks (if task file exists)
if [ -f ~/.openclaw/workspace/tasks.md ]; then
    echo "✅ Pending tasks:"
    grep -E "^- \\[ \\]" ~/.openclaw/workspace/tasks.md | head -5
    echo ""
fi

# Check yesterday's work (git commits)
echo "💻 Yesterday's commits:"
if [ -d .git ]; then
    git log --since="yesterday" --oneline --author="$(git config user.name)" | head -5
else
    echo "  (Not in a git repository)"
fi
echo ""

# Prompt for today's goals
echo "🎯 What are your goals for today?"
echo "  (Type your goals, press Ctrl+D when done)"
echo ""

goals=$(cat)

# Save to daily log
log_file=~/.openclaw/workspace/daily_standup_$(date +%Y%m%d).md
cat > "$log_file" << EOF
# Daily Standup - $(date +'%Y-%m-%d')

## Goals
$goals

## Calendar
(See OpenClaw message above)

## Yesterday
$(git log --since="yesterday" --oneline --author="$(git config user.name)" 2>/dev/null || echo "No commits")
EOF

echo "✅ Standup saved to: $log_file"
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add to crontab (run daily at {standup_time}):
   0 9 * * * {script_path}
4. Or run manually each morning
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '20 min/week'
    }


# Template registry
PRODUCTIVITY_TEMPLATES = {
    'focus_mode': template_focus_mode,
    'context_switch': template_context_switch,
    'pomodoro_timer': template_pomodoro_timer,
    'daily_standup': template_daily_standup
}
