#!/usr/bin/env python3
"""
System Administration Templates for V8 Code Generator

Provides 5 new template types:
1. log_rotation - Auto-rotate logs when they exceed size threshold
2. disk_cleanup - Clean old files when disk usage is high
3. service_restart - Restart services with exponential backoff
4. health_check - Periodic endpoint health checks
5. backup_automation - Automated directory backups with retention
"""

from pathlib import Path
from typing import Dict


def template_log_rotation(pattern: Dict, output_dir: Path) -> Dict:
    """Generate log rotation automation"""
    log_path = pattern.get('log_path', '/var/log/app.log')
    max_size_mb = pattern.get('max_size_mb', 100)
    keep_count = pattern.get('keep_count', 5)
    
    script_name = f"rotate_{Path(log_path).stem}_logs"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated log rotation script
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

LOG_PATH="{log_path}"
MAX_SIZE_MB={max_size_mb}
KEEP_COUNT={keep_count}

# Check if log exists
if [ ! -f "$LOG_PATH" ]; then
    echo "Log file not found: $LOG_PATH" >&2
    exit 0
fi

# Get current size in MB
size_mb=$(du -m "$LOG_PATH" | cut -f1)

if [ $size_mb -ge $MAX_SIZE_MB ]; then
    echo "Rotating log: $LOG_PATH ($size_mb MB >= $MAX_SIZE_MB MB)"
    
    # Create timestamped backup
    timestamp=$(date +%Y%m%d_%H%M%S)
    backup="${{LOG_PATH}}.${{timestamp}}"
    
    cp "$LOG_PATH" "$backup"
    gzip "$backup"
    
    # Truncate original log
    > "$LOG_PATH"
    
    echo "Log rotated to: ${{backup}}.gz"
    
    # Clean up old rotations (keep last N)
    ls -t "${{LOG_PATH}}".*.gz 2>/dev/null | tail -n +$((KEEP_COUNT + 1)) | xargs -r rm -f
    
    echo "Kept $KEEP_COUNT most recent backups"
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add to crontab (run hourly):
   0 * * * * {script_path}
4. Or run manually when needed
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '10 min/week'
    }


def template_disk_cleanup(pattern: Dict, output_dir: Path) -> Dict:
    """Generate disk cleanup automation"""
    threshold_percent = pattern.get('threshold_percent', 80)
    cleanup_paths = pattern.get('cleanup_paths', [
        '~/.cache',
        '~/Library/Caches',
        '/tmp',
        '~/Downloads'
    ])
    
    script_name = "disk_cleanup"
    script_path = output_dir / f"{script_name}.sh"
    
    paths_str = '\n'.join([f'    "{p}"' for p in cleanup_paths])
    
    code = f'''#!/bin/bash
#
# Auto-generated disk cleanup script
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

THRESHOLD={threshold_percent}

# Get current disk usage percentage
usage=$(df -h / | awk 'NR==2 {{print $5}}' | sed 's/%//')

echo "Current disk usage: ${{usage}}%"

if [ $usage -ge $THRESHOLD ]; then
    echo "⚠️  Disk usage above ${{THRESHOLD}}% threshold, cleaning up..."
    
    # Cleanup paths
    cleanup_paths=(
{paths_str}
    )
    
    freed=0
    
    for path in "${{cleanup_paths[@]}}"; do
        # Expand tilde
        expanded=$(eval echo "$path")
        
        if [ -d "$expanded" ]; then
            echo "Cleaning: $expanded"
            
            # Get size before
            before=$(du -sk "$expanded" 2>/dev/null | cut -f1)
            
            # Remove files older than 30 days
            find "$expanded" -type f -mtime +30 -delete 2>/dev/null
            
            # Get size after
            after=$(du -sk "$expanded" 2>/dev/null | cut -f1)
            
            if [ -n "$before" ] && [ -n "$after" ]; then
                freed=$((freed + before - after))
            fi
        fi
    done
    
    freed_mb=$((freed / 1024))
    echo "✅ Freed ${{freed_mb}} MB"
    
    # Check new usage
    new_usage=$(df -h / | awk 'NR==2 {{print $5}}' | sed 's/%//')
    echo "New disk usage: ${{new_usage}}%"
else
    echo "✅ Disk usage OK (${{usage}}% < ${{THRESHOLD}}%)"
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add to crontab (run daily at 3 AM):
   0 3 * * * {script_path}
4. Or run manually when disk is full
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '15 min/week'
    }


def template_service_restart(pattern: Dict, output_dir: Path) -> Dict:
    """Generate service restart with exponential backoff"""
    service_name = pattern.get('service_name', 'myapp')
    max_retries = pattern.get('max_retries', 5)
    check_command = pattern.get('check_command', f'launchctl list | grep {service_name}')
    restart_command = pattern.get('restart_command', f'launchctl kickstart -k gui/$UID/{service_name}')
    
    script_name = f"restart_{service_name}"
    script_path = output_dir / f"{script_name}.sh"
    
    code = f'''#!/bin/bash
#
# Auto-generated service restart script with exponential backoff
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

SERVICE="{service_name}"
MAX_RETRIES={max_retries}
CHECK_CMD="{check_command}"
RESTART_CMD="{restart_command}"

echo "Checking service: $SERVICE"

if eval "$CHECK_CMD" &>/dev/null; then
    echo "✅ Service is running"
    exit 0
fi

echo "⚠️  Service not running, attempting restart..."

attempt=1
while [ $attempt -le $MAX_RETRIES ]; do
    echo "Attempt $attempt/$MAX_RETRIES"
    
    # Restart service
    eval "$RESTART_CMD"
    
    # Exponential backoff: 2^attempt seconds
    wait_time=$((2 ** attempt))
    echo "Waiting ${{wait_time}}s..."
    sleep $wait_time
    
    # Check if service is running
    if eval "$CHECK_CMD" &>/dev/null; then
        echo "✅ Service restarted successfully"
        exit 0
    fi
    
    attempt=$((attempt + 1))
done

echo "❌ Failed to restart service after $MAX_RETRIES attempts"
exit 1
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Use in V6/V7 service monitoring
4. Or run manually when service fails
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '20 min/week'
    }


def template_health_check(pattern: Dict, output_dir: Path) -> Dict:
    """Generate periodic health check script"""
    endpoints = pattern.get('endpoints', ['http://localhost:8080/health'])
    timeout = pattern.get('timeout', 10)
    notify_on_failure = pattern.get('notify', True)
    
    script_name = "health_check"
    script_path = output_dir / f"{script_name}.sh"
    
    endpoints_str = ' '.join([f'"{e}"' for e in endpoints])
    
    notify_code = '''
        # Notify via Telegram
        if [ -f ~/.openclaw/workspace/integrations/intelligence/v8_meta_learning/telegram_notifier.py ]; then
            python3 ~/.openclaw/workspace/integrations/intelligence/v8_meta_learning/telegram_notifier.py "Health check failed: $endpoint"
        fi''' if notify_on_failure else '        # Notification disabled'
    
    code = f'''#!/bin/bash
#
# Auto-generated health check script
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

ENDPOINTS=({endpoints_str})
TIMEOUT={timeout}
FAILURES=0

for endpoint in "${{ENDPOINTS[@]}}"; do
    echo "Checking: $endpoint"
    
    if curl -sf --max-time $TIMEOUT "$endpoint" > /dev/null; then
        echo "✅ $endpoint OK"
    else
        echo "❌ $endpoint FAILED"
        FAILURES=$((FAILURES + 1))
{notify_code}
    fi
done

if [ $FAILURES -eq 0 ]; then
    echo "✅ All health checks passed"
    exit 0
else
    echo "❌ $FAILURES/${{#ENDPOINTS[@]}} checks failed"
    exit 1
fi
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add to crontab (run every 5 minutes):
   */5 * * * * {script_path}
4. Or integrate with V7 self-healing
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '30 min/week'
    }


def template_backup_automation(pattern: Dict, output_dir: Path) -> Dict:
    """Generate automated backup script"""
    source_dirs = pattern.get('source_dirs', ['~/Documents', '~/workspace'])
    backup_dest = pattern.get('backup_dest', '~/Backups')
    retention_days = pattern.get('retention_days', 30)
    
    script_name = "automated_backup"
    script_path = output_dir / f"{script_name}.sh"
    
    sources_str = ' '.join([f'"{d}"' for d in source_dirs])
    
    code = f'''#!/bin/bash
#
# Auto-generated backup automation script
# Generated by V8 Code Generator
# Pattern confidence: {pattern.get('confidence', 0.0):.0%}
#

SOURCE_DIRS=({sources_str})
BACKUP_DEST="{backup_dest}"
RETENTION_DAYS={retention_days}

# Expand tilde
BACKUP_DEST=$(eval echo "$BACKUP_DEST")

# Create backup directory if it doesn't exist
mkdir -p "$BACKUP_DEST"

# Generate timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

echo "Starting backup at $TIMESTAMP"

for source in "${{SOURCE_DIRS[@]}}"; do
    # Expand tilde
    expanded=$(eval echo "$source")
    
    if [ ! -d "$expanded" ]; then
        echo "⚠️  Source not found: $expanded"
        continue
    fi
    
    # Get directory name for backup file
    dirname=$(basename "$expanded")
    backup_file="${{BACKUP_DEST}}/${{dirname}}_${{TIMESTAMP}}.tar.gz"
    
    echo "Backing up: $expanded → $backup_file"
    
    tar -czf "$backup_file" -C "$(dirname "$expanded")" "$(basename "$expanded")" 2>/dev/null
    
    if [ $? -eq 0 ]; then
        size=$(du -h "$backup_file" | cut -f1)
        echo "✅ Backup complete: $size"
    else
        echo "❌ Backup failed: $expanded"
    fi
done

# Clean up old backups
echo "Cleaning up backups older than $RETENTION_DAYS days..."
find "$BACKUP_DEST" -name "*.tar.gz" -mtime +$RETENTION_DAYS -delete

echo "✅ Backup complete"
'''
    
    install = f'''# Installation:
1. Save to: {script_path}
2. Make executable: chmod +x {script_path}
3. Add to crontab (run daily at 2 AM):
   0 2 * * * {script_path}
4. Customize source_dirs and backup_dest as needed
'''
    
    return {
        'script_path': script_path,
        'script_name': script_name,
        'code': code,
        'language': 'bash',
        'install_instructions': install,
        'estimated_savings': '25 min/week'
    }


# Template registry for easy lookup
SYSTEM_ADMIN_TEMPLATES = {
    'log_rotation': template_log_rotation,
    'disk_cleanup': template_disk_cleanup,
    'service_restart': template_service_restart,
    'health_check': template_health_check,
    'backup_automation': template_backup_automation
}
