#!/usr/bin/env python3
"""
Non-Technical Approval Messages

Format LLM-generated code proposals as non-technical, user-friendly messages.
Never show raw code to users - only show what it does, why it helps, and what changes.
"""

from typing import Dict


def format_approval_message(pattern: Dict, generated_code: Dict) -> str:
    """
    Format an approval message for LLM-generated automation.
    
    User sees:
    - What the automation does (plain English)
    - Why it's recommended (time savings, frequency)
    - What will change (behavior differences)
    - Risk level (low/medium/high)
    - Actions they can take (Approve / View Details / Decline)
    
    User does NOT see:
    - Raw Python/Bash code
    - Technical implementation details
    - Function names or API calls
    """
    
    # Extract non-technical fields
    title = generated_code.get('user_title', 'New Automation')
    explanation = generated_code.get('user_explanation', 'Automates a detected pattern')
    why = generated_code.get('why_recommended', 'Based on your usage patterns')
    what_changes = generated_code.get('what_changes', 'Adds automation to your workflow')
    risk = generated_code.get('risk_level', 'medium')
    
    # Risk emoji
    risk_emoji = {
        'low': '🟢',
        'medium': '🟡',
        'high': '🔴'
    }.get(risk, '🟡')
    
    # Format message (NO CODE SHOWN)
    message = f"""🤖 **New Automation Available**

**{title}**

{explanation}

**Why this helps:**
{why}

**What changes:**
{what_changes}

**Safety:** {risk_emoji} {risk.capitalize()} risk

**Actions:**
✅ Approve - Deploy this automation
ℹ️ Details - See technical specs (optional)
❌ Decline - Not interested

This automation was generated by AI and has been safety-validated.
"""
    
    return message


def format_technical_details(pattern: Dict, generated_code: Dict) -> str:
    """
    Format optional technical details for users who want to see implementation.
    
    Still avoids raw code, but shows:
    - Script name and language
    - Key steps the automation takes
    - Files it will create/modify
    - Permissions needed
    """
    
    script_name = generated_code.get('script_name', 'automation_script')
    language = generated_code.get('language', 'python')
    code = generated_code.get('code', '')
    
    # Extract key steps from code (simplified)
    steps = _extract_steps_from_code(code, language)
    
    message = f"""🔧 **Technical Details**

**Script:** `{script_name}`
**Language:** {language.capitalize()}

**What it does (step-by-step):**
"""
    
    for i, step in enumerate(steps, 1):
        message += f"{i}. {step}\n"
    
    message += f"""
**Files created:**
• ~/.openclaw/workspace/scripts/{script_name}

**Permissions:**
• Read/write access to workspace directory
• No elevated (sudo) access required

**Code review:**
The full source code is available for inspection in the deployment manager.
Contact support if you'd like a technical review before deployment.
"""
    
    return message


def _extract_steps_from_code(code: str, language: str) -> list:
    """
    Extract high-level steps from code without showing raw implementation.
    
    Returns:
        List of plain-English step descriptions
    """
    steps = []
    
    # Look for common patterns and describe them in plain English
    if 'import' in code:
        steps.append("Import required tools")
    
    if 'def ' in code or 'function' in code:
        steps.append("Define automation workflow")
    
    if 'try:' in code or 'catch' in code:
        steps.append("Add error handling for reliability")
    
    if 'log' in code.lower():
        steps.append("Log actions for debugging")
    
    if 'subprocess' in code or 'run' in code:
        steps.append("Execute the detected command pattern")
    
    if 'retry' in code.lower():
        steps.append("Retry failed operations automatically")
    
    if 'cache' in code.lower():
        steps.append("Cache results to avoid re-running")
    
    if 'email' in code.lower():
        steps.append("Interact with email system")
    
    if 'calendar' in code.lower():
        steps.append("Interact with calendar system")
    
    if 'file' in code.lower() or 'open(' in code:
        steps.append("Read/write files in workspace")
    
    # Generic fallback
    if not steps:
        steps = [
            "Load configuration",
            "Execute automation logic",
            "Return results"
        ]
    
    return steps


def format_post_deployment_summary(pattern: Dict, generated_code: Dict, result: Dict) -> str:
    """
    Format a success message after deployment (also non-technical).
    """
    
    script_name = generated_code.get('script_name', 'automation')
    title = generated_code.get('user_title', 'Automation')
    
    message = f"""✅ **Automation Deployed Successfully**

**{title}** is now active.

**What's different:**
• The automation runs automatically when triggered
• You'll see fewer manual steps in your workflow
• Logs are saved to: ~/.openclaw/workspace/logs/

**Testing:**
Try triggering the pattern naturally and watch it work!

**Managing:**
• Disable: Run `hobbes disable {script_name}`
• Remove: Run `hobbes remove {script_name}`
• Logs: Run `hobbes logs {script_name}`

Questions? Just ask me to explain what it's doing.
"""
    
    return message


# Example usage
if __name__ == '__main__':
    # Test with mock data
    pattern = {
        'type': 'recurring_meeting',
        'title': 'Weekly Standup',
        'count': 52,
        'confidence': 0.95
    }
    
    generated_code = {
        'user_title': 'Auto-prep Weekly Standup',
        'user_explanation': 'Automatically create agenda doc 30 minutes before your Weekly Standup meeting',
        'why_recommended': 'You have this meeting 52 times per year and often scramble to prepare',
        'what_changes': 'An agenda document will appear in your Google Drive before each meeting',
        'risk_level': 'low',
        'script_name': 'weekly_standup_prep',
        'language': 'python',
        'code': '#!/usr/bin/env python3\nimport google_calendar\n...'
    }
    
    # Non-technical approval message (what user sees by default)
    print(format_approval_message(pattern, generated_code))
    print("\n" + "="*50 + "\n")
    
    # Technical details (optional, if user clicks "Details")
    print(format_technical_details(pattern, generated_code))
